[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/questions/:category"
  to = "/.netlify/functions/questions-category"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
